name: Build & Deploy
on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy gspataro
        uses: appleboy/ssh-action@v1.1.0
        with:
          host: ${{secrets.SSH_HOST}}
          key: ${{secrets.SSH_KEY}}
          username: ${{secrets.SSH_USER}}
          passphrase: ${{secrets.SSH_PASSPHRASE}}

          script: |
            cd giuseppespataro.it
            git pull
            npm install
            composer install
            composer run build
            echo 'Successfully deployed.'
